(function(){
  function safe(s){try{return Utils.escapeHtml(String(s??''))}catch(e){return String(s??'')}}
  window.courierAssignmentCard=function(a){
    const offered=a.status==='offered', accepted=a.status==='accepted', arrived=a.status==='arrived';
    const active=accepted||arrived;
    const label=offered?'Nouvelle mission':accepted?'En route':arrived?'Arrivé':'Terminée';
    const cls=offered?'offer':arrived?'arrived':active?'active':'done';
    return `<article class="courier-pro-card ${cls}">
      <div class="courier-pro-card-top"><div class="courier-order-badge"><span>#</span>${safe(a.order_number||'—')}</div><span class="courier-pro-status ${cls}"><i></i>${label}</span></div>
      <div class="courier-destination"><div class="courier-destination-icon">${ICO_PIN_SVG}</div><div class="courier-destination-copy"><span>DESTINATION</span><b>${safe(a.customer_name||'Client')}</b><p>${safe(a.customer_address||'Adresse non renseignée')}</p></div></div>
      <div class="courier-pro-metrics"><div><span>RÉMUNÉRATION</span><b>${a.amount!=null?Utils.fmtFCFA(a.amount):'—'}</b></div><div><span>DISTANCE</span><b id="courier-dist-${a.id}">…</b></div></div>
      ${offered?`<div class="courier-offer-timer" data-courier-timer="${a.id}">${ICO_CLOCK_SVG}<span>Réponse sous 10:00</span></div>
      <div class="courier-pro-actions"><div class="courier-eta-field"><label>ARRIVÉE ESTIMÉE</label><select id="eta-${a.id}"><option value="30">30 min</option><option value="45">45 min</option><option value="60">1 h</option><option value="90">1 h 30</option><option value="120">2 h</option></select></div><div class="courier-action-row"><button class="courier-secondary-btn" onclick="declineCourierDelivery('${a.id}')">Refuser</button><button class="courier-primary-btn" onclick="acceptCourierDelivery('${a.id}')">Accepter <span>→</span></button></div></div>`:''}
      ${accepted?`<div class="courier-confirmed-strip"><span>✓</span><div><b>Mission acceptée</b><small>Rendez-vous à l'adresse du client.</small></div></div><button class="courier-primary-btn full" onclick="courierArrived('${a.id}')">📍 Je suis arrivé</button><div class="courier-action-row"><button class="courier-secondary-btn" onclick="CourierMission.open('${a.id}')">Mission</button><button class="courier-secondary-btn" onclick="startCourierLiveGps('${a.id}')">GPS</button></div>`:''}
      ${arrived?`<div class="courier-arrived-panel"><div class="courier-arrived-icon">✓</div><div><b>Vous êtes arrivé</b><small>Attendez la confirmation de réception du client.</small></div></div><button class="courier-primary-btn full" onclick="CourierMission.open('${a.id}')">Ouvrir la mission</button>`:''}
      <button class="courier-route-btn" onclick="window.open('https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent((a.customer_latitude||'')+','+(a.customer_longitude||'')),'_blank')">⌖ Ouvrir l'itinéraire</button>
    </article>`;
  };

  Views['courier-dashboard']=function(){
    const sess=courierSession(); if(!sess) return Views['courier-login']();
    const name=safe(sess.name||'Livreur'), initials=((sess.name||'L').trim().split(/\s+/).map(w=>w[0]).filter(Boolean).slice(0,2).join('')||'L').toUpperCase(), online=CourierApp.isOnline();
    return `<div class="courier-premium-shell">
      <header class="courier-premium-header"><div class="courier-premium-head-row"><div class="courier-profile-mini"><div class="courier-avatar premium-avatar">${initials}</div><div class="courier-profile-copy"><div class="courier-kicker">ESPACE LIVREUR</div><div class="courier-premium-name">${name}<span id="courier-cert-badge-hero"></span></div></div></div>
      <div class="courier-head-actions"><button class="courier-icon-btn" onclick="CourierNotify.open()" aria-label="Notifications">♧<span class="courier-notif-dot" id="courier-v42-dot"></span></button><button class="courier-icon-btn" onclick="setCourierSession(null);Router.go('courier-login')" aria-label="Déconnexion">↪</button></div></div>
      <div class="courier-availability-card"><div><div class="courier-availability-label">Disponibilité</div><div class="courier-availability-sub">${online?'Vous pouvez recevoir de nouvelles missions':'Vous ne recevrez pas de nouvelles missions'}</div></div><button id="courier-online-btn" class="courier-premium-online ${online?'online':'offline'}" onclick="CourierApp.toggleOnline()"><span class="courier-live-dot"></span>${online?'EN LIGNE':'HORS LIGNE'}</button></div></header>
      <main id="courier-page-body" class="courier-premium-body">
        <div class="courier-tab-panel active" data-tab="dashboard"><div class="courier-welcome"><div><div class="courier-eyebrow">TABLEAU DE BORD</div><h1>Bonjour ${name.split(' ')[0]} 👋</h1><p>Suivez vos livraisons en temps réel.</p></div><div class="courier-route-mark">⌖</div></div>
        <div id="courier-stats-mount" class="courier-premium-stats"><div class="courier-premium-stat"><span>À TRAITER</span><b>—</b></div><div class="courier-premium-stat active"><span>EN COURS</span><b>—</b></div></div>
        <div class="courier-section-head"><div><div class="courier-eyebrow">PRIORITÉ</div><h2>Livraisons à traiter</h2></div><button class="courier-see-all" onclick="CourierApp.setTab('missions')">Tout voir ›</button></div><div id="courier-dashboard-list"><div class="wd-spinner"></div></div></div>
        <div class="courier-tab-panel" data-tab="missions"><div class="courier-section-head solo"><div><div class="courier-eyebrow">ACTIVITÉ</div><h2>Toutes mes missions</h2></div></div><div id="courier-missions-list"><div class="wd-spinner"></div></div></div>
        <div class="courier-tab-panel" data-tab="gains"><div class="courier-section-head solo"><div><div class="courier-eyebrow">FINANCES</div><h2>Mes gains</h2></div></div><div id="courier-earnings-mount"><div class="wd-spinner"></div></div></div>
        <div class="courier-tab-panel" data-tab="profil"><div class="courier-profile-hero"><div class="courier-avatar premium-avatar large">${initials}</div><div><div class="courier-eyebrow">MON PROFIL</div><div class="courier-profile-big-name">${name}<span id="courier-cert-badge"></span></div><div class="courier-profile-role">Livreur SIAMS</div></div></div><div id="courier-profile-stats" class="courier-premium-stats triple"><div class="courier-premium-stat"><span>ACCEPTATION</span><b>—</b></div><div class="courier-premium-stat"><span>MISSIONS</span><b>—</b></div><div class="courier-premium-stat"><span>CE MOIS</span><b>—</b></div></div><div class="courier-section-head solo"><div><div class="courier-eyebrow">VERSEMENTS</div><h2>Solde à verser</h2></div></div><div id="courier-payout-list"><div class="wd-spinner"></div></div><div class="courier-section-head solo"><div><div class="courier-eyebrow">VÉRIFICATION</div><h2>Documents</h2></div></div><div id="courier-docs-list"><div class="wd-spinner"></div></div><div class="courier-section-head solo"><div><div class="courier-eyebrow">PRÉFÉRENCES</div><h2>Paramètres</h2></div></div><div id="courier-settings-list"></div><button class="courier-logout-wide" onclick="setCourierSession(null);Router.go('courier-login')">Se déconnecter</button></div>
      </main>
      <nav class="courier-premium-nav"><button class="courier-nav-btn active" data-tab="dashboard" onclick="CourierApp.setTab('dashboard')"><span class="courier-nav-ico">⌂</span><span>Accueil</span></button><button class="courier-nav-btn" data-tab="missions" onclick="CourierApp.setTab('missions')"><span class="courier-nav-ico">▤</span><span>Missions</span></button><button class="courier-nav-btn" data-tab="gains" onclick="CourierApp.setTab('gains')"><span class="courier-nav-ico">↗</span><span>Gains</span></button><button class="courier-nav-btn" data-tab="profil" onclick="CourierApp.setTab('profil')"><span class="courier-nav-ico">◯</span><span>Profil</span></button></nav>
    </div>`;
  };
})();
