(function(){
 const oldGo=Router.go.bind(Router);
 const money=n=>{try{return Utils.fmtFCFA(Number(n)||0)}catch(e){return (Number(n)||0)+' FCFA'}};
 const panel=(t,s,b)=>`<section class="v14-merchant-panel"><div class="v14-kicker">Service SIAMS</div><h2 class="v14-title">${t}</h2><p class="v14-sub">${s}</p>${b}</section>`;
 function enhance(name){const root=document.getElementById('page-root');if(!root||!['customers','delivery','team','boutique'].includes(name))return;root.querySelectorAll('.v14-merchant-panel').forEach(x=>x.remove());let h='';
 if(name==='customers'){const c=Store.customers(),o=c.reduce((a,x)=>a+(+x.orders||0),0),v=c.reduce((a,x)=>a+(+x.spent||0),0),f=c.filter(x=>x.isTopContributor).length;h=panel('Pilotage clients','Suivez la fidélité et la valeur de vos clients.',`<div class="v14-grid"><div class="v14-stat"><b>${c.length}</b><span>Clients connus</span></div><div class="v14-stat"><b>${o}</b><span>Commandes</span></div><div class="v14-stat"><b>${money(v)}</b><span>Dépenses cumulées</span></div><div class="v14-stat"><b>${f}</b><span>Clients fidèles</span></div></div><div style="height:10px"></div><div class="v14-actions"><button class="v14-action" onclick="Router.go('orders')"><strong>🧾 Historique</strong><small>Commandes clients</small></button><button class="v14-action" onclick="Router.go('reviews')"><strong>⭐ Satisfaction</strong><small>Avis clients</small></button></div>`)}
 if(name==='delivery'){const o=Store.orders||[],z=Store.deliveryZones||[],d=o.filter(x=>x.status==='delivered').length,p=o.filter(x=>['pending','confirmed','preparing','shipped'].includes(x.status)).length,a=o.length?Math.round(o.reduce((s,x)=>s+(+x.deliveryFee||0),0)/o.length):0;h=panel('Centre livraison','Pilotez les zones, les frais et les livraisons.',`<div class="v14-grid"><div class="v14-stat"><b>${p}</b><span>À traiter / en cours</span></div><div class="v14-stat"><b>${d}</b><span>Livrées</span></div><div class="v14-stat"><b>${z.length}</b><span>Zones</span></div><div class="v14-stat"><b>${money(a)}</b><span>Frais moyen</span></div></div><div style="height:10px"></div><div class="v14-actions"><button class="v14-action" onclick="Router.go('orders')"><strong>🚚 Voir les commandes</strong><small>Suivre les livraisons</small></button><button class="v14-action" onclick="addDeliveryZone()"><strong>＋ Ajouter une zone</strong><small>Frais et délai</small></button></div>`)}
 if(name==='team'){const t=Store.team||[],c=Store.couriers||[],a=t.filter(x=>['Admin','Administrateur','Propriétaire'].includes(x.role)).length;h=panel('Centre équipe','Organisez les rôles et la collaboration de votre boutique.',`<div class="v14-grid"><div class="v14-stat"><b>${t.length}</b><span>Membres</span></div><div class="v14-stat"><b>${t.filter(x=>x.status!=='suspended').length}</b><span>Actifs</span></div><div class="v14-stat"><b>${a}</b><span>Administrateurs</span></div><div class="v14-stat"><b>${c.length}</b><span>Livreurs</span></div></div><div style="height:10px"></div><div class="v14-actions"><button class="v14-action" onclick="openAddMember()"><strong>＋ Ajouter un membre</strong><small>Gérant, vendeur, admin</small></button><button class="v14-action" onclick="inviteCourierFromMerchant()"><strong>🚚 Inviter un livreur</strong><small>Invitation SIAMS</small></button></div>`)}
 if(name==='boutique'){const st=Store.store||{},p=Store.products||[],cats=[...new Set(p.map(x=>x.category).filter(Boolean))];h=panel('Centre boutique','Gérez votre vitrine, votre catalogue et votre visibilité.',`<div class="v14-grid"><div class="v14-stat"><b>${p.length}</b><span>Produits</span></div><div class="v14-stat"><b>${cats.length}</b><span>Catégories</span></div><div class="v14-stat"><b>★ 4,8</b><span>Note boutique</span></div><div class="v14-stat"><b>${st.name?'Active':'À compléter'}</b><span>Profil</span></div></div><div style="height:10px"></div><div class="v14-actions"><button class="v14-action" onclick="Router.go('store-edit')"><strong>✎ Modifier la vitrine</strong><small>Logo, bannière, infos</small></button><button class="v14-action" onclick="Router.go('products')"><strong>🛍️ Catalogue</strong><small>Produits, prix, stocks</small></button><button class="v14-action" onclick="Router.go('categories')"><strong>▦ Catégories</strong><small>Organiser le catalogue</small></button><button class="v14-action" onclick="Router.go('banners')"><strong>🖼️ Bannières</strong><small>Carrousel en haut de la boutique</small></button><button class="v14-action" onclick="Router.go('showcase')"><strong>📢 Cournsel client</strong><small>Annonces &amp; partenariats</small></button><button class="v14-action" onclick="Router.go('shop',{skipOnboarding:true})"><strong>👁 Aperçu client</strong><small>Voir la boutique</small></button></div>`)}
 root.insertAdjacentHTML('afterbegin',h)}
 Router.go=function(n,o){oldGo(n,o);setTimeout(()=>enhance(n),0)};window.SIAMS_V14={enhance};
})();
